apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: website
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend_demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: website
    spec:
      containers:
      - image: 192.168.0.7:32000/frontend:test
        name: frontend
        resources: {}
status: {}
