kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: portfolio
  labels:
    app: frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: frontend
  type: ClusterIP
