stages:
  - tmp

tmp:
  stage: tmp
  image:
    name: registry.gitlab.com/mariuspod/kaniko/executor-debug-arm:latest
    entrypoint: [""]
  tags:
    - k8s
  script:
    - echo "{\"auths\":{\"$CI_LOCAL_REGISTRY\":{\"username\":\"$CI_PRIVATE_REGISTRY_USER\",\"password\":\"$CI_PRIVATE_REGISTRY_PASSWORD\",\"email\":\"$CI_PRIVATE_REGISTRY_EMAIL\",\"auth\":\"$CI_PRIVATE_REGISTRY_AUTH\"""}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --insecure-registry 192.168.0.7:32000 --context $CI_PROJECT_DIR/frontend/ --dockerfile frontend/Dockerfile --destination $CI_LOCAL_FRONTEND_IMAGE:testing1 