stages:
  - launch
  - build
  - test
  - deploy
  - teardown

launch_build_machine:
  stage: launch
  script:
    - who
    - whoami
    - aws ec2 start-instances --instance-ids "$BUILD_MACHINE_ID"

pull_changes:
  stage: build
  script:
    - ssh -tt -i $CREDENTIAL_FILE $BUILD_MACHINE_USER@$BUILD_MACHINE_IP "cd /lib/gitlab/builds/springexercise; git checkout develop; git pull"

front_end_build:
  stage: build
  script:
    - echo "Building front end"
    - ssh -tt -i $CREDENTIAL_FILE $BUILD_MACHINE_USER@$BUILD_MACHINE_IP "cd /lib/gitlab/builds/springexercise; cd frontend; npm install; ng build"

deploy_front_end:
  stage: deploy
  script:
    - echo "pulling code from build server"
    - scp -r -i $CREDENTIAL_FILE $BUILD_MACHINE_USER@$BUILD_MACHINE_IP:/lib/gitlab/builds/springexercise/frontend/dist/frontend/ /var/www/frontend/dist/
  after_script:
    - sudo service nginx restart


stop_build_machine:
  stage: teardown
  script:
    - aws ec2 stop-instances --instance-ids $BUILD_MACHINE_ID
