stages:
  - build
  - test
  - deploy

front_end_build:
  stage: build
  script:
    - echo "Building front end"
    - ng build

#spring_build:
#  stage: build
#  script:
#    - echo "Building spring boot"
#    - ssh -tt -i $CREDENTIAL_FILE $BUILD_MACHINE_USER@$BUILD_MACHINE_IP "cd /lib/gitlab/builds/springexercise; cd javaservice; gradle bootWar"

deploy_front_end:
  stage: deploy
  script:
    - echo "pulling code from build server"
    - scp -r -i "C:\Users\devin\Documents\Amazon EC2 Keys\githubec2.pem" dist\frontend ubuntu@ec2-34-209-39-218.us-west-2.compute.amazonaws.com:/var/www/frontend/dist/