stages:
  - launch
  - build
  - test
  - deploy
  - teardown

launch_build_machine:
  stage: launch
  script:
    - aws ec2 start-instances --instance-ids $BUILD_MACHINE_ID

ssh_to_build_machine:
  stage: build
  script:
    - ssh -i $CREDENTIAL_FILE $BUILD_MACHINE_USER@$BUILD_MACHINE_IP
    - cd /lib/gitlab/builds/springexercise
    - git checkout develop
    - git fetch

continue_in_build:
  stage: test
  script:
    - echo "is this working from the right machine?"
  after_script:
    - exit

#front_end_build:
#  stage: build
#  script:
#    - echo "Building front end"
#    - cd frontend
#    - npm install
#    - ng build

stop_build_machine:
  stage: teardown
  script:
    - aws ec2 stop-instances --instance-ids $BUILD_MACHINE_ID
