stages:
  - build
  - test
  - deploy

front_end_build:
  stage: build
  script:
    - dir
    - cd frontend
    - echo "Building front end"
    - npm install
    - npm run ng build

#spring_build:
#  stage: build
#  script:
#    - echo "Building spring boot"
#    - ssh -tt -i $CREDENTIAL_FILE $BUILD_MACHINE_USER@$BUILD_MACHINE_IP "cd /lib/gitlab/builds/springexercise; cd javaservice; gradle bootWar"

deploy_front_end:
  variables:
    GIT_CHECKOUT: "false"   
  stage: deploy
  script:
    - echo "pulling code from build server"
    - scp -r -i  $SERVER_KEY dist\frontend $FRONTEND_DIST