stages:
  - pull
  - build
  - test
  - deploy

pull_from_gitlab:
  stage: pull
  script:
    - echo "Pulling from GitLab"

front_end_build:
  variables:
    GIT_CHECKOUT: "false"   
  stage: build
  script:
    - dir
    - cd frontend
    - echo "Building front end"
    - npm install
    - npm run ng build --prod --configuration production

spring_build:
  variables:
    GIT_CHECKOUT: "false"   
  stage: build
  script:
    - echo "Building spring boot"
    - cd javaservice
    - gradle bootWar

deploy_front_end:
  variables:
    GIT_CHECKOUT: "false"   
  stage: deploy
  script:
    - echo "pulling code from build server"
    - cd frontend
    - Start-Process 'C:\Program Files\PuTTY\pscp.exe' -ArgumentList("-scp -r -i  $SERVER_KEY dist\frontend $FRONTEND_DIST")

deploy_back_end:
  variables:
    GIT_CHECKOUT: "false"   
  stage: deploy
  script:
    - echo "pushing tomcat"
    - cd javaservice
    - Start-Process 'C:\Program Files\PuTTY\pscp.exe' -ArgumentList("-scp -r -i  $SERVER_KEY build\libs\spring-exercise-1.war $BACKEND_DIST")