stages:
  - tmp

tmp:
  stage: tmp
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\"}}" > /kaniko/.docker/config.json
  tags:
      - k8s