stages:
  - tmp

tmp:
  stage: tmp
  tags:
      - k8s
  image:
    name: gcr.io/kaniko-project/executor:arm64
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\"}}" > /kaniko/.docker/config.json
    