apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: 192.168.0.7:32000/backend:<tag_here>
        name: backend
        resources: {}
        volumeMounts:
          - name: application-properties
            mountPath: /opt/conf/
            readOnly: false
      volumes:
        - name: application-properties
          secret:
            secretName: springboot-application-properties
status: {}
